=== wensttay/pos-atv-xml-reader/src/main/java/br/edu/ifpb/ads/pos/atv/xml/reader/parcer/examples/computador.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3schools.com"
           xmlns="http://www.w3schools.com"
           elementFormDefault="qualified">
    
    <xs:element name="computador">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="marca" type="xs:string"/>
                <xs:element name="modelo" type="xs:string"/>
                <xs:element name="cor" type="xs:string"/>
                <xs:element ref="processador" minOccurs='1' maxOccurs='unbounded'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="processador">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="numeroDeSerie" type="xs:string"/>
                <xs:element name="geracao" type="xs:string"/> 
                <xs:element name="descricao" type="xs:string"/> 
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== wensttay/pos-atv-xml-reader/src/main/java/br/edu/ifpb/ads/pos/atv/xml/reader/parcer/examples/outputFile.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<computador xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com computador.xsd">
    <marca>Apple</marca>
    <modelo>X1</modelo>
    <cor>Black</cor>
    <processador>
        <numeroDeSerie>2001</numeroDeSerie>
        <geracao>Quinta</geracao>
        <descricao>Potente</descricao>
    </processador>
</computador>

=== wensttay/pos-atv-xml-reader/src/main/java/br/edu/ifpb/ads/pos/atv/xml/reader/parcer/examples/computador.xml
<?xml version="1.0" encoding="UTF-8" ?>
<computador 
    xmlns="http://www.w3schools.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.w3schools.com computador.xsd">

    <marca>Microsoft</marca>
    <modelo>Japones</modelo>
    <cor>Silver</cor>
    <processador>
        <numeroDeSerie>2932</numeroDeSerie>
        <geracao>Decima</geracao>
        <descricao>Gamer</descricao>
    </processador>
    
</computador>
